runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /src/client/(.+)
  static_files: src/client/\1
  upload: src/client/.*

- url: /
  static_files: src/client/index.html
  upload: src/client/index.html
